/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 if the process is up. No dependency checks.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks the Postgres, Redis, RPC, and Turnkey dependencies.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All dependencies responded healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessStatus"];
                    };
                };
                /** @description One or more dependencies is down. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new agent
         * @description Provisions a Turnkey MPC wallet, optionally deploys a Safe smart
         *     wallet, and returns the plaintext API key **once**. The plaintext
         *     cannot be recovered later.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAgentRequest"];
                };
            };
            responses: {
                /** @description Agent registered. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateAgentResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public agent search */
        get: {
            parameters: {
                query: {
                    /** @description Search term (matches name or safeAddress). */
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Up to 10 matching active agents. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            agents?: components["schemas"]["AgentSearchResult"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current agent (resolved from API key) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own service manifest */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Arbitrary JSON describing tools/services you offer. */
                        manifest: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Manifest saved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            serviceManifest?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/agents/me/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profit & loss breakdown
         * @description Earnings minus costs (protocol fees, A2A rewards paid out, gas).
         *     Gas cost = `gasUsed * effectiveGasPriceWei` per CONFIRMED/REVERTED tx.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional ISO 8601 period start. Defaults to `createdAt`. */
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description P&L breakdown. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PnLBreakdown"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/sign-handshake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign an A2A handshake (not implemented) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                501: components["responses"]["NotImplemented"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/verify-handshake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a peer's handshake (not implemented) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                501: components["responses"]["NotImplemented"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        /** Agent details (owner only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent profile with policy + billing. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Soft deactivate + emergency pause */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent deactivated. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update operational policy */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePolicyRequest"];
                };
            };
            responses: {
                /** @description Updated policy. When `syncOnChain=true`, also returns calldata for on-chain sync. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdatePolicyResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/v1/agents/{id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        /** Fetch a peer agent's service manifest (public) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Manifest. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            name?: string;
                            safeAddress?: string;
                            ensName?: string | null;
                            serviceManifest?: {
                                [key: string]: unknown;
                            } | null;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/trust-report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        /** Reputation and trust metrics (public) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trust report. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrustReport"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run a Uniswap V3 swap */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SimulateSwapRequest"];
                };
            };
            responses: {
                /** @description Simulation outcome. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationResult"];
                    };
                };
                422: components["responses"]["SimulationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a Uniswap V3 swap */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExecuteSwapRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                403: components["responses"]["PolicyViolation"];
                409: components["responses"]["IdempotencyConflict"];
                422: components["responses"]["SimulationFailed"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ETH or ERC-20 transfer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransferRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                403: components["responses"]["PolicyViolation"];
                409: components["responses"]["IdempotencyConflict"];
                422: components["responses"]["SimulationFailed"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Supply to Aave V3 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetAmountRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                403: components["responses"]["PolicyViolation"];
                409: components["responses"]["IdempotencyConflict"];
                422: components["responses"]["SimulationFailed"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw from Aave V3 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetAmountRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                403: components["responses"]["PolicyViolation"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/supply-compound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Supply to Compound V3 (Comet USDC market) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetAmountRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                400: components["responses"]["BadRequest"];
                403: components["responses"]["PolicyViolation"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/withdraw-compound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw from Compound V3 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetAmountRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/deposit-erc4626": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposit into any ERC-4626 vault */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Erc4626Request"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                403: components["responses"]["PolicyViolation"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/withdraw-erc4626": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw from any ERC-4626 vault */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Erc4626Request"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/swap-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Swap on a Curve StableSwap pool */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CurveSwapRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                403: components["responses"]["PolicyViolation"];
                422: components["responses"]["SimulationFailed"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute up to 20 actions atomically via the AgentExecutor */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchRequest"];
                };
            };
            responses: {
                202: components["responses"]["TransactionAccepted"];
                400: components["responses"]["BadRequest"];
                403: components["responses"]["PolicyViolation"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated transaction history (current agent) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    status?: components["schemas"]["TxStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of transactions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Transaction status (owner only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full transaction record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Public transaction view (limited fields) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public transaction fields. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicTransaction"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Safe + EOA addresses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Addresses. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WalletAddresses"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Native and ERC-20 balances */
        get: {
            parameters: {
                query?: {
                    /** @description EVM chain ID (1=Ethereum, 8453=Base, 42161=Arbitrum, 137=Polygon). */
                    chainId?: components["parameters"]["ChainIdQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balances. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WalletBalance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/allowances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active token allowances */
        get: {
            parameters: {
                query?: {
                    /** @description EVM chain ID (1=Ethereum, 8453=Base, 42161=Arbitrum, 137=Polygon). */
                    chainId?: components["parameters"]["ChainIdQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Allowances. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            allowances?: components["schemas"]["Allowance"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Stripe Checkout Session (upgrade to PRO) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checkout URL. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url?: string;
                        };
                    };
                };
                /** @description Already subscribed to a paid tier. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe customer portal URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Portal URL. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook receiver (signature verified)
         * @description Called by Stripe. Request must be signed with `Stripe-Signature`
         *     and the raw request body is used for verification. Do not call
         *     directly.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Acknowledged. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Signature verification failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscription state + usage this period */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Billing status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a service request for another agent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateJobRequest"];
                };
            };
            responses: {
                /** @description Job created. If `reward` was specified, funds are reserved atomically. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description Escrow reservation failed (daily volume would be exceeded). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs assigned to me (as provider) */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["JobStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Jobs list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobs?: components["schemas"]["Job"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs I created (as requester) */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["JobStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Jobs list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobs?: components["schemas"]["Job"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Job detail (requester or provider only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transition a job status
         * @description Valid transitions:
         *     - `PENDING` → `ACCEPTED` | `CANCELLED`
         *     - `ACCEPTED` → `COMPLETED` | `FAILED` | `CANCELLED`
         *
         *     When transitioning to `COMPLETED`, escrow is released and
         *     `executeA2APayment()` runs automatically if a reward was set.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateJobRequest"];
                };
            };
            responses: {
                /** @description Updated job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description Invalid status transition. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard overview */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stats. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All agents with billing */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agents. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        /** Single agent detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        /** Agent transaction history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transactions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emergency kill switch (toggle) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pause toggled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{id}/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent CUID. */
                id: components["parameters"]["AgentIdPath"];
            };
            cookie?: never;
        };
        /** P&L for any agent (admin view) */
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path: {
                    /** @description Agent CUID. */
                    id: components["parameters"]["AgentIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description P&L breakdown. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PnLBreakdown"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global transaction log */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transactions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transactions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Operator batch execution */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch queued. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transactions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a PENDING_APPROVAL transaction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transactions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a PENDING_APPROVAL transaction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rejected. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily volume chart (7 days) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Daily volume series. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revenue breakdown by tier */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revenue. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reputation/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute reputation (all or single agent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description If provided, only this agent is recomputed. */
                        agentId?: string;
                    };
                };
            };
            responses: {
                /** @description Recompute result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reputation/{agentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        /** Reputation detail (persisted vs computed drift) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reputation detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream for MCP tool calls
         * @description Opens an SSE stream. Clients post JSON-RPC messages to
         *     `/mcp/messages?sessionId=<id>` and receive results here.
         *
         *     **Note:** This endpoint exposes a thin 16-tool proxy. The
         *     standalone `@agent_fi/mcp-server` npm package offers 26 tools
         *     including A2A collaboration — prefer it when possible.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** JSON-RPC message handler (paired with /mcp/sse) */
        post: {
            parameters: {
                query: {
                    sessionId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Accepted. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable message. */
            error: string;
            /** @description Optional additional context (string, object, or array). */
            details?: unknown;
        };
        HealthStatus: {
            /** @example ok */
            status?: string;
            uptime?: number;
        };
        ReadinessStatus: {
            /** @enum {string} */
            status?: "ok" | "degraded";
            checks?: {
                [key: string]: "ok" | "fail";
            };
        };
        /** @enum {string} */
        AgentTier: "FREE" | "PRO" | "ENTERPRISE";
        /** @enum {string} */
        TxStatus: "SIMULATING" | "PENDING_APPROVAL" | "QUEUED" | "SUBMITTED" | "CONFIRMED" | "FAILED" | "REVERTED";
        /** @enum {string} */
        JobStatus: "PENDING" | "ACCEPTED" | "COMPLETED" | "FAILED" | "CANCELLED";
        CreateAgentRequest: {
            name: string;
            /**
             * @default [
             *       1
             *     ]
             */
            chainIds: number[];
            tier?: components["schemas"]["AgentTier"];
            policy?: components["schemas"]["Policy"];
        };
        CreateAgentResponse: {
            id: string;
            name: string;
            /**
             * @description Plaintext — shown once, never stored. Keep it safe.
             * @example agfi_live_abc123...
             */
            apiKey: string;
            apiKeyPrefix?: string;
            walletAddress?: string;
            safeAddress: string;
            chainIds: number[];
            tier: components["schemas"]["AgentTier"];
            /** @description ENS subdomain pointing at the Safe address. Null when ENS isn't configured. */
            ensName?: string | null;
        };
        AgentSearchResult: {
            id?: string;
            name?: string;
            chainIds?: number[];
            tier?: components["schemas"]["AgentTier"];
        };
        Agent: {
            id?: string;
            name?: string;
            apiKeyPrefix?: string;
            walletAddress?: string;
            ensName?: string | null;
            chainIds?: number[];
            active?: boolean;
            tier?: components["schemas"]["AgentTier"];
            policy?: components["schemas"]["Policy"] | null;
            billing?: {
                txCountThisPeriod?: number;
                totalFeesCollectedUsd?: string;
                subscriptionActive?: boolean;
            } | null;
        };
        Policy: {
            /** @example 1.0 */
            maxValuePerTxEth?: string;
            /** @example 10000 */
            maxDailyVolumeUsd?: string;
            allowedContracts?: string[];
            allowedTokens?: string[];
            /** @default 60 */
            cooldownSeconds: number;
            /** @default true */
            active: boolean;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        UpdatePolicyRequest: components["schemas"]["Policy"] & {
            /**
             * @description If true, response includes calldata for on-chain policy sync.
             * @default false
             */
            syncOnChain: boolean;
        };
        UpdatePolicyResponse: components["schemas"]["Policy"] & {
            onChainSync?: {
                to?: string;
                chainId?: number;
                actions?: {
                    to?: string;
                    value?: string;
                    data?: string;
                }[];
                notice?: string;
            } | null;
        };
        TrustReport: {
            id?: string;
            name?: string;
            reputationScore?: number;
            a2aTxCount?: number;
            /** Format: date-time */
            lastActiveAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PnLBreakdown: {
            agentId?: string;
            name?: string;
            /** Format: date-time */
            periodStart?: string;
            /** Format: date-time */
            periodEnd?: string;
            earnings?: {
                a2aJobsAsProvider?: components["schemas"]["CountUsd"];
                totalEarningsUsd?: string;
            };
            costs?: {
                protocolFees?: components["schemas"]["CountUsd"];
                a2aJobsAsRequester?: components["schemas"]["CountUsd"];
                gas?: components["schemas"]["CountUsd"];
                totalCostsUsd?: string;
            };
            netPnlUsd?: string;
            breakEven?: boolean;
            profitable?: boolean;
            notes?: string[];
        };
        CountUsd: {
            count?: number;
            usd?: string;
        };
        SimulateSwapRequest: {
            fromToken: string;
            toToken: string;
            /** @description Human-readable decimal amount (not wei). */
            amountIn: string;
            /** @default 1 */
            chainId: number;
            /** @default 0.5 */
            slippageTolerance: number;
        };
        ExecuteSwapRequest: components["schemas"]["SimulateSwapRequest"] & {
            simulationId: string;
            idempotencyKey?: string;
        };
        TransferRequest: {
            /** @description "ETH" or an ERC-20 contract address. */
            token: string;
            to: string;
            amount: string;
            /** @default 1 */
            chainId: number;
            idempotencyKey?: string;
        };
        AssetAmountRequest: {
            /** @description Token address. */
            asset: string;
            /** @description Human-readable decimal amount, or "max" for withdraws. */
            amount: string;
            /** @default 1 */
            chainId: number;
            idempotencyKey?: string;
        };
        Erc4626Request: {
            /** @description Vault contract address. */
            vault: string;
            /** @description Underlying token (for decimals + pricing). */
            asset: string;
            amount: string;
            /** @default 1 */
            chainId: number;
            idempotencyKey?: string;
        };
        CurveSwapRequest: {
            pool: string;
            fromTokenIndex: number;
            toTokenIndex: number;
            fromTokenAddress: string;
            toTokenAddress: string;
            amountIn: string;
            minAmountOut: string;
            /** @default 1 */
            chainId: number;
            idempotencyKey?: string;
        };
        BatchRequest: {
            /** @default 1 */
            chainId: number;
            idempotencyKey?: string;
            actions: {
                to: string;
                /** @default 0 */
                value: string;
                /** @default 0x0000000000000000000000000000000000000000 */
                token: string;
                /** @default 0x */
                data: string;
            }[];
        };
        TransactionAccepted: {
            transactionId?: string;
            status?: components["schemas"]["TxStatus"];
            fee?: {
                bps?: number;
                amountWei?: string;
                feeWallet?: string;
            } | null;
        };
        Transaction: {
            id?: string;
            agentId?: string;
            chainId?: number;
            txHash?: string | null;
            status?: components["schemas"]["TxStatus"];
            /** @enum {string} */
            type?: "SWAP" | "TRANSFER" | "DEPOSIT" | "WITHDRAW" | "BATCH";
            fromToken?: string | null;
            toToken?: string | null;
            amountIn?: string | null;
            amountOut?: string | null;
            gasUsed?: string | null;
            effectiveGasPriceWei?: string | null;
            error?: string | null;
            simulation?: {
                [key: string]: unknown;
            } | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            confirmedAt?: string | null;
        };
        PublicTransaction: {
            id?: string;
            chainId?: number;
            status?: components["schemas"]["TxStatus"];
            type?: string;
            txHash?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            confirmedAt?: string | null;
        };
        TransactionPage: {
            transactions?: components["schemas"]["Transaction"][];
            nextCursor?: string | null;
        };
        SimulationResult: {
            simulationId?: string;
            success?: boolean;
            gasEstimate?: string;
            amountOut?: string;
            error?: string | null;
        };
        WalletAddresses: {
            safeAddress?: string;
            eoaAddress?: string;
        };
        WalletBalance: {
            chainId?: number;
            native?: {
                wei?: string;
                formatted?: string;
                usd?: string;
            };
            tokens?: {
                address?: string;
                symbol?: string;
                decimals?: number;
                balance?: string;
                usd?: string;
            }[];
        };
        Allowance: {
            token?: string;
            spender?: string;
            amount?: string;
        };
        BillingStatus: {
            tier?: components["schemas"]["AgentTier"];
            subscriptionActive?: boolean;
            /** Format: date-time */
            subscriptionPeriodEnd?: string | null;
            txCountThisPeriod?: number;
            txLimitThisPeriod?: number | null;
            totalFeesCollectedUsd?: string;
        };
        JobReward: {
            amount?: string;
            /** @default ETH */
            token: string;
            /** @default 1 */
            chainId: number;
        };
        CreateJobRequest: {
            /** @description CUID of the agent that will execute this job. */
            providerId: string;
            payload: {
                [key: string]: unknown;
            };
            reward?: components["schemas"]["JobReward"];
            signature?: string;
        };
        UpdateJobRequest: {
            /** @enum {string} */
            status: "ACCEPTED" | "COMPLETED" | "FAILED" | "CANCELLED";
            result?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        Job: {
            id?: string;
            requesterId?: string;
            providerId?: string;
            status?: components["schemas"]["JobStatus"];
            payload?: {
                [key: string]: unknown;
            };
            reward?: components["schemas"]["JobReward"] | null;
            signature?: string | null;
            result?: {
                [key: string]: unknown;
            } | null;
            reservedAmount?: string | null;
            reservedToken?: string | null;
            reservedChainId?: number | null;
            /** Format: date-time */
            reservedAt?: string | null;
            /** @enum {string|null} */
            reservationStatus?: "PENDING" | "RELEASED" | "CANCELLED" | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: {
        /** @description Validation failed or malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Access denied (wrong agent or insufficient permissions). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The `idempotencyKey` is in use by another agent. */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Action blocked by the agent's operational policy. */
        PolicyViolation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description On-chain simulation reverted or produced an error before broadcast. */
        SimulationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Monthly transaction limit reached for the agent's tier. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Feature is not yet implemented (blocked on external integration). */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The request is valid, policy-approved, and has been queued.
         *     The transaction will be broadcast by a background worker.
         */
        TransactionAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TransactionAccepted"];
            };
        };
    };
    parameters: {
        /** @description Agent CUID. */
        AgentIdPath: string;
        /** @description EVM chain ID (1=Ethereum, 8453=Base, 42161=Arbitrum, 137=Polygon). */
        ChainIdQuery: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
